//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinMeum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitcoinMeum.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AboutAuthorText {
            get {
                return ResourceManager.GetString("AboutAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string AboutButtonCopyAddress {
            get {
                return ResourceManager.GetString("AboutButtonCopyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string AboutEmailText {
            get {
                return ResourceManager.GetString("AboutEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string AboutVersionDescriptionText {
            get {
                return ResourceManager.GetString("AboutVersionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutVersionText {
            get {
                return ResourceManager.GetString("AboutVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2f2f2f.
        /// </summary>
        public static string ApplicationBackcolor {
            get {
                return ResourceManager.GetString("ApplicationBackcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string ApplicationPlainTextColor {
            get {
                return ResourceManager.GetString("ApplicationPlainTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0071C5.
        /// </summary>
        public static string ApplicationTileBackcolor {
            get {
                return ResourceManager.GetString("ApplicationTileBackcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0071C5.
        /// </summary>
        public static string ApplicationTileBordercolor {
            get {
                return ResourceManager.GetString("ApplicationTileBordercolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string ApplicationTileTextcolor {
            get {
                return ResourceManager.GetString("ApplicationTileTextcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITCOIN MEUM.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0071C5.
        /// </summary>
        public static string ApplicationTitleTextColor {
            get {
                return ResourceManager.GetString("ApplicationTitleTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will be available soon..
        /// </summary>
        public static string AvailableSoon {
            get {
                return ResourceManager.GetString("AvailableSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t refresh wallet balance. Please set your wallet. My wallet &gt; Settings..
        /// </summary>
        public static string BalanceRefreshFailed {
            get {
                return ResourceManager.GetString("BalanceRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t refresh wallet balance. Please check your internet connection..
        /// </summary>
        public static string BalanceRefreshFailedConnection {
            get {
                return ResourceManager.GetString("BalanceRefreshFailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE SCAN.
        /// </summary>
        public static string BalanceScannerTitle {
            get {
                return ResourceManager.GetString("BalanceScannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BalanceScannerTitleRef {
            get {
                return ResourceManager.GetString("BalanceScannerTitleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITCOIN GUIDE.
        /// </summary>
        public static string BitcoinGuideTitle {
            get {
                return ResourceManager.GetString("BitcoinGuideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin guide.
        /// </summary>
        public static string BitcoinGuideTitleRef {
            get {
                return ResourceManager.GetString("BitcoinGuideTitleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoinDesk.
        /// </summary>
        public static string CoinDesk {
            get {
                return ResourceManager.GetString("CoinDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1KAqjkCjQiWYnpjmNWWb7zsDGJEFLVbUDQ.
        /// </summary>
        public static string DonateAddress {
            get {
                return ResourceManager.GetString("DonateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation:.
        /// </summary>
        public static string DonateAddressText {
            get {
                return ResourceManager.GetString("DonateAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bistamp.
        /// </summary>
        public static string MarketsBitstampTitle {
            get {
                return ResourceManager.GetString("MarketsBitstampTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btc-e.
        /// </summary>
        public static string MarketsBtceTitle {
            get {
                return ResourceManager.GetString("MarketsBtceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETS.
        /// </summary>
        public static string MarketsTitle {
            get {
                return ResourceManager.GetString("MarketsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string MarketsTitleRef {
            get {
                return ResourceManager.GetString("MarketsTitleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balance.
        /// </summary>
        public static string MWBalanceTitle {
            get {
                return ResourceManager.GetString("MWBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount!.
        /// </summary>
        public static string MWInvalidRequestAmount {
            get {
                return ResourceManager.GetString("MWInvalidRequestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string MWRefreshBalance {
            get {
                return ResourceManager.GetString("MWRefreshBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request.
        /// </summary>
        public static string MWRequestTitle {
            get {
                return ResourceManager.GetString("MWRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string MWSendAmount {
            get {
                return ResourceManager.GetString("MWSendAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount!.
        /// </summary>
        public static string MWSendAmountError {
            get {
                return ResourceManager.GetString("MWSendAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockchain response:.
        /// </summary>
        public static string MWSendBlockchainResponse {
            get {
                return ResourceManager.GetString("MWSendBlockchainResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string MWSendButton {
            get {
                return ResourceManager.GetString("MWSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has been canceled!.
        /// </summary>
        public static string MWSendCancel {
            get {
                return ResourceManager.GetString("MWSendCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee (≥0.0001).
        /// </summary>
        public static string MWSendFee {
            get {
                return ResourceManager.GetString("MWSendFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string MWSendMessage {
            get {
                return ResourceManager.GetString("MWSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key has not been entered!.
        /// </summary>
        public static string MWSendPrivateKeyError {
            get {
                return ResourceManager.GetString("MWSendPrivateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipient address!.
        /// </summary>
        public static string MWSendRecipientError {
            get {
                return ResourceManager.GetString("MWSendRecipientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string MWSendTitle {
            get {
                return ResourceManager.GetString("MWSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string MWSendTo {
            get {
                return ResourceManager.GetString("MWSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLET SETTINGS.
        /// </summary>
        public static string MWSettings {
            get {
                return ResourceManager.GetString("MWSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MWSettingsRef {
            get {
                return ResourceManager.GetString("MWSettingsRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key.
        /// </summary>
        public static string MWSPrivate {
            get {
                return ResourceManager.GetString("MWSPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        public static string MWSPublic {
            get {
                return ResourceManager.GetString("MWSPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC:.
        /// </summary>
        public static string MWTransactionAmount {
            get {
                return ResourceManager.GetString("MWTransactionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string MWTransactionMessage {
            get {
                return ResourceManager.GetString("MWTransactionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transactions.
        /// </summary>
        public static string MWTransactionsTitle {
            get {
                return ResourceManager.GetString("MWTransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY WALLET.
        /// </summary>
        public static string MyWalletTitle {
            get {
                return ResourceManager.GetString("MyWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My wallet.
        /// </summary>
        public static string MyWalletTitleRef {
            get {
                return ResourceManager.GetString("MyWalletTitleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsTitleRef {
            get {
                return ResourceManager.GetString("NewsTitleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering valid Private key enables user option to send bitcoins via Blockchain API..
        /// </summary>
        public static string PrivateKeyWalletDescription {
            get {
                return ResourceManager.GetString("PrivateKeyWalletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option enables users to add watch-only bitcoin address by entering it&apos;s public key.
        ///As a result you can keep track of wallet transactions, current balance and receive bitcoins via QR..
        /// </summary>
        public static string PublicKeyWalletDescription {
            get {
                return ResourceManager.GetString("PublicKeyWalletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin is still an experiment..
        /// </summary>
        public static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t own bitcoins if you don&apos;t have the private keys..
        /// </summary>
        public static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always backup your wallet..
        /// </summary>
        public static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin is a protocol, not a currency. Currency is just the first app. .
        /// </summary>
        public static string Q4 {
            get {
                return ResourceManager.GetString("Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information at www.bitcoin.org.
        /// </summary>
        public static string Q5 {
            get {
                return ResourceManager.GetString("Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial renaissance..
        /// </summary>
        public static string Q6 {
            get {
                return ResourceManager.GetString("Q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, Satoshi and bitcoin core devs..
        /// </summary>
        public static string Q7 {
            get {
                return ResourceManager.GetString("Q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you even hodl? :).
        /// </summary>
        public static string Q8 {
            get {
                return ResourceManager.GetString("Q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High:.
        /// </summary>
        public static string RatesDayHigh {
            get {
                return ResourceManager.GetString("RatesDayHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low:.
        /// </summary>
        public static string RatesDayLow {
            get {
                return ResourceManager.GetString("RatesDayLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        public static string RatesDayVolume {
            get {
                return ResourceManager.GetString("RatesDayVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last:.
        /// </summary>
        public static string RatesLast {
            get {
                return ResourceManager.GetString("RatesLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated:.
        /// </summary>
        public static string RatesTimestamp {
            get {
                return ResourceManager.GetString("RatesTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r/Bitcoin.
        /// </summary>
        public static string rBitcoin {
            get {
                return ResourceManager.GetString("rBitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more ....
        /// </summary>
        public static string RSSReadMore {
            get {
                return ResourceManager.GetString("RSSReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tile.
        /// </summary>
        public static string SettingsLiveTile {
            get {
                return ResourceManager.GetString("SettingsLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet balance instead (Medium).
        /// </summary>
        public static string TileBalanceInstead {
            get {
                return ResourceManager.GetString("TileBalanceInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable live tile.
        /// </summary>
        public static string TileEnableText {
            get {
                return ResourceManager.GetString("TileEnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Bitstamp price will be updated every 30 seconds.
        /// </summary>
        public static string TileLastBitstampText {
            get {
                return ResourceManager.GetString("TileLastBitstampText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string UIButtonFontSize {
            get {
                return ResourceManager.GetString("UIButtonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string UIRegularTextSize {
            get {
                return ResourceManager.GetString("UIRegularTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string UISmallTextSize {
            get {
                return ResourceManager.GetString("UISmallTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        public static string UITextBoxFontSize {
            get {
                return ResourceManager.GetString("UITextBoxFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTC:.
        /// </summary>
        public static string WalletBalanceText {
            get {
                return ResourceManager.GetString("WalletBalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD:.
        /// </summary>
        public static string WalletBalanceUSD {
            get {
                return ResourceManager.GetString("WalletBalanceUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QR.
        /// </summary>
        public static string WalletCreateRequestQRText {
            get {
                return ResourceManager.GetString("WalletCreateRequestQRText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallet generator.
        /// </summary>
        public static string WalletGeneratorTitle {
            get {
                return ResourceManager.GetString("WalletGeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet generator.
        /// </summary>
        public static string WalletGeneratorTitleRef {
            get {
                return ResourceManager.GetString("WalletGeneratorTitleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total received:.
        /// </summary>
        public static string WalletTotalReceivedText {
            get {
                return ResourceManager.GetString("WalletTotalReceivedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sent:.
        /// </summary>
        public static string WalletTotalSentText {
            get {
                return ResourceManager.GetString("WalletTotalSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions:.
        /// </summary>
        public static string WalletTransactionCountText {
            get {
                return ResourceManager.GetString("WalletTransactionCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITCOIN BASICS.
        /// </summary>
        public static string WelcomeGoToBitcoinBasics {
            get {
                return ResourceManager.GetString("WelcomeGoToBitcoinBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        public static string WelcomeGoToMenu {
            get {
                return ResourceManager.GetString("WelcomeGoToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Bitcoin Meum!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to take a tour through bitcoin basics?.
        /// </summary>
        public static string WelcomeTourText {
            get {
                return ResourceManager.GetString("WelcomeTourText", resourceCulture);
            }
        }
    }
}
